services:
  postgres:
    image: postgres:latest
    container_name: postgres-auth
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: authpass
    ports:
    - "5432:5432"
